### ISSUE TITLE
Hi, is there a way/code to generate landmarks for custom images? 

### ISSUE THREAD

**Issue by anant-pathak** [LynnHo/Facial-Landmarks-of-Face-Datasets#1]

**Comment by LynnHo** [comment]
@anantthebiker This repo only provides landmarks. If you want landmark prediction, you should use tools like `dlib` or `mtcnn`.

**Comment by anant-pathak** [comment]
@LynnHo thanks a lot for pointing me in the right direction. I believe in order to crop a face using your other repo: https://github.com/LynnHo/HD-CelebA-Cropper I'd need to find 69 facial landmark as opposed to 5 facial landmarks(through mtcnn) ?

**Comment by LynnHo** [comment]
@anantthebiker 68 and 5 are both ok for cropping with their corresponding standard landmarks. [HD-CelebA-Cropper](https://github.com/LynnHo/HD-CelebA-Cropper) provides 68 landmark annotations of CelebA dataset. For other datasets, you should predict the landmarks first.
